import turtle
turtle.Screen().bgcolor("black")
turtle.pencolor("black")
turtle.up()
turtle.goto(50,100)
turtle.down()
turtle.fillcolor('yellow')
turtle.begin_fill()
turtle.circle(100,70)
turtle.left(110)
turtle.circle(100,70)
turtle.end_fill()
turtle.up()
turtle.goto(50,100)
turtle.down()


turtle.fillcolor('yellow')
turtle.begin_fill()
turtle.circle(100,70)
turtle.left(110)
turtle.circle(100,70)
turtle.end_fill()


turtle.fillcolor('yellow')
turtle.begin_fill()
turtle.circle(100,70)
turtle.left(110)
turtle.circle(100,70)
turtle.end_fill()

turtle.fillcolor('yellow')
turtle.begin_fill()
turtle.circle(100,70)
turtle.left(110)
turtle.circle(100,70)
turtle.end_fill()

turtle.fillcolor('yellow')
turtle.begin_fill()
turtle.circle(100,70)
turtle.left(110)
turtle.circle(100,70)
turtle.end_fill()

turtle.fillcolor('yellow')
turtle.begin_fill()
turtle.circle(100,70)
turtle.left(110)
turtle.circle(100,70)
turtle.end_fill()

turtle.fillcolor('yellow')
turtle.begin_fill()
turtle.circle(100,70)
turtle.left(110)
turtle.circle(100,70)
turtle.end_fill()

turtle.fillcolor('yellow')
turtle.begin_fill()
turtle.circle(100,70)
turtle.left(110)
turtle.circle(100,70)
turtle.end_fill()

turtle.fillcolor('yellow')
turtle.begin_fill()
turtle.circle(100,70)
turtle.left(110)
turtle.circle(100,70)
turtle.end_fill()

turtle.fillcolor('yellow')
turtle.begin_fill()
turtle.circle(100,70)
turtle.left(110)
turtle.circle(100,70)
turtle.end_fill()

turtle.fillcolor('yellow')
turtle.begin_fill()
turtle.circle(100,70)
turtle.left(110)
turtle.circle(100,70)
turtle.end_fill()

turtle.fillcolor('yellow')
turtle.begin_fill()
turtle.circle(100,70)
turtle.left(110)
turtle.circle(100,70)
turtle.end_fill()

turtle.fillcolor('yellow')
turtle.begin_fill()
turtle.circle(100,70)
turtle.left(110)
turtle.circle(100,70)
turtle.end_fill()

#ikinci çiçek
turtle.up()
turtle.goto(-100,-100)
turtle.down()
turtle.fillcolor('white')
turtle.begin_fill()
turtle.circle(100,70)
turtle.left(110)
turtle.circle(100,70)
turtle.end_fill()
turtle.up()
turtle.goto(-100,-100)
turtle.down()


turtle.fillcolor('white')
turtle.begin_fill()
turtle.circle(100,70)
turtle.left(110)
turtle.circle(100,70)
turtle.end_fill()


turtle.fillcolor('white')
turtle.begin_fill()
turtle.circle(100,70)
turtle.left(110)
turtle.circle(100,70)
turtle.end_fill()

turtle.fillcolor('white')
turtle.begin_fill()
turtle.circle(100,70)
turtle.left(110)
turtle.circle(100,70)
turtle.end_fill()

turtle.fillcolor('white')
turtle.begin_fill()
turtle.circle(100,70)
turtle.left(110)
turtle.circle(100,70)
turtle.end_fill()

turtle.fillcolor('white')
turtle.begin_fill()
turtle.circle(100,70)
turtle.left(110)
turtle.circle(100,70)
turtle.end_fill()

turtle.fillcolor('white')
turtle.begin_fill()
turtle.circle(100,70)
turtle.left(110)
turtle.circle(100,70)
turtle.end_fill()

turtle.fillcolor('white')
turtle.begin_fill()
turtle.circle(100,70)
turtle.left(110)
turtle.circle(100,70)
turtle.end_fill()

turtle.fillcolor('white')
turtle.begin_fill()
turtle.circle(100,70)
turtle.left(110)
turtle.circle(100,70)
turtle.end_fill()

turtle.fillcolor('white')
turtle.begin_fill()
turtle.circle(100,70)
turtle.left(110)
turtle.circle(100,70)
turtle.end_fill()

turtle.fillcolor('white')
turtle.begin_fill()
turtle.circle(100,70)
turtle.left(110)
turtle.circle(100,70)
turtle.end_fill()

turtle.fillcolor('white')
turtle.begin_fill()
turtle.circle(100,70)
turtle.left(110)
turtle.circle(100,70)
turtle.end_fill()

turtle.fillcolor('white')
turtle.begin_fill()
turtle.circle(100,70)
turtle.left(110)
turtle.circle(100,70)
turtle.end_fill()



turtle.getscreen()._root.mainloop()