import turtle
turtle.Screen().bgcolor("black")
def colored_star():
    size = 10
    turtle.color("white")
    turtle.width(2)
    angle = 120
    for side in range(5):
        turtle.forward(size)
        turtle.right(angle)
        turtle.forward(size)
        turtle.right(72 - angle)
    turtle.end_fill()
    turtle.penup()
    turtle.setposition(-120, 0)
    turtle.pendown()
    for side in range(5):
        turtle.forward(size)
        turtle.right(angle)
        turtle.forward(size)
        turtle.right(72 - angle)
    turtle.end_fill()
    turtle.penup()
    turtle.setposition(60, 60)
    turtle.pendown()
    for side in range(5):
        turtle.forward(size)
        turtle.right(angle)
        turtle.forward(size)
        turtle.right(72 - angle)
    turtle.end_fill()
    turtle.penup()
    turtle.setposition(180, 60)
    turtle.pendown()
    for side in range(5):
        turtle.forward(size)
        turtle.right(angle)
        turtle.forward(size)
        turtle.right(72 - angle)
    turtle.end_fill()
    turtle.penup()
    turtle.setposition(90, 140)
    turtle.pendown()
    for side in range(5):
        turtle.forward(size)
        turtle.right(angle)
        turtle.forward(size)
        turtle.right(72 - angle)
    turtle.end_fill()
    turtle.penup()
    turtle.setposition(-30, 140)
    turtle.pendown()
    for side in range(5):
        turtle.forward(size)
        turtle.right(angle)
        turtle.forward(size)
        turtle.right(72 - angle)
    turtle.end_fill()
    turtle.penup()
    turtle.setposition(-100, 180)
    turtle.pendown()
    for side in range(5):
        turtle.forward(size)
        turtle.right(angle)
        turtle.forward(size)
        turtle.right(72 - angle)
    turtle.end_fill()
    turtle.penup()
    turtle.setposition(-300, 180)
    turtle.pendown()
    for side in range(5):
        turtle.forward(size)
        turtle.right(angle)
        turtle.forward(size)
        turtle.right(72 - angle)
    turtle.end_fill()
    turtle.penup()
    turtle.setposition(-300, -90)
    turtle.pendown()
    for side in range(5):
        turtle.forward(size)
        turtle.right(angle)
        turtle.forward(size)
        turtle.right(72 - angle)
    turtle.end_fill()
    turtle.penup()
    turtle.setposition(-250, -30)
    turtle.pendown()
    for side in range(5):
        turtle.forward(size)
        turtle.right(angle)
        turtle.forward(size)
        turtle.right(72 - angle)
    turtle.end_fill()
colored_star()
turtle.getscreen()._root.mainloop()


